"""Bilingual interface: English by default, Chinese one click away.

The design decision here is what the *key* is. Inventing keys (`overview.title`)
means every string has to be looked up in two places to be read, and a missing
key renders as `overview.title` in front of a user. So the English source text is
the key: `t("Overview")` returns the Chinese if there is one and the English if
there is not. A missing translation degrades to correct English rather than to a
placeholder, and the code stays readable in its own right.

Why this product needs it at all: the explanations *are* the argument. A screen
that says "26.9% routed to a person" in Chinese and then explains why that number
is the cost of the recall in English has translated the labels and left the
reasoning behind.

What is deliberately NOT translated:
  * identifiers - `CASE_0001121`, `R303_IMPOSSIBLE_TRAVEL`, `txn.captured_minor`;
  * currency codes and money;
  * generated content - rule details, AI briefs, audit summaries. These come from
    the pipeline and the model, not the interface, and machine-translating a
    signal's detail string would put a translation error inside evidence.
That last one is a limitation, stated on screen rather than hidden.
"""

from __future__ import annotations

import streamlit as st

LANGUAGES = {"en": "English", "zh": "中文"}
DEFAULT_LANGUAGE = "en"

# English source text -> Chinese. Everything not in here falls back to English.
ZH: dict[str, str] = {
    # --- chrome and shared ---------------------------------------------
    "CrossBorder RiskOps": "CrossBorder RiskOps 跨境支付风险运营工作台",
    "Cross-border payment risk operations workbench": "跨境支付风险运营工作台",
    "Last build": "最近构建",
    "seed": "随机种子",
    "validation": "校验",
    "rules": "规则",
    "model": "模型",
    "taxonomy": "分类体系",
    "reporting cut-off": "报告截止日",
    "Language": "语言",
    "**AI boundary.** The copilot organises evidence and *recommends*. "
    "It cannot release, hold, refund or close anything. Those are committed by a person "
    "or by the deterministic policy, and the audit log refuses to record an AI actor on a "
    "decision.":
        "**AI 边界。** 副驾驶整理证据并*提出建议*。它不能放行、拦截、退款或结案——"
        "这些由人或确定性策略引擎提交,审计日志拒绝把 AI 记录为决策执行者。",
    "The warehouse has not been built yet. Run this once, then reload:":
        "数据仓库尚未构建。先运行一次,然后刷新页面:",
    "Interface language only. Rule details, AI briefs and audit entries are shown as the "
    "pipeline and the model produced them — translating evidence would put a translation "
    "error inside it.":
        "仅界面语言切换。规则明细、AI 简报和审计记录按流水线与模型生成的原文展示——"
        "翻译证据等于把翻译误差放进证据里。",

    # --- the synthetic-data banner -------------------------------------
    "Synthetic data · simulated environment.": "合成数据 · 模拟环境。",
    "Every transaction, merchant, wallet, device and risk label on this screen was generated by a "
    "seeded script. Nothing here has touched a real payment network, bank, merchant or customer, "
    "and no figure describes a real business outcome.":
        "本页面上的每一笔交易、商户、钱包、设备和风险标签都由固定随机种子的脚本生成。"
        "这里没有任何内容接触过真实支付网络、银行、商户或客户,也没有任何数字描述真实业务结果。",
    "Decisions taken on this screen are written to the local warehouse and are part of the demo.":
        "本页面上做出的决策会写入本地数据仓库,属于演示的一部分。",

    # --- Overview -------------------------------------------------------
    "Overview": "总览",
    "One synthetic cross-border payment estate, the risk signals it produced, and the case "
    "queue that came out of it.":
        "一套合成的跨境支付资产、它产生的风险信号,以及由此形成的案件队列。",
    "Transactions": "交易笔数",
    "Cross-border": "跨境交易",
    "Payment events": "支付事件",
    "Quarantined events": "隔离事件",
    "Reconciliation breaks": "对账差异",
    "Every payment in the reporting window.": "报告窗口内的每一笔支付。",
    "Payer and merchant in different countries, or two currencies involved.":
        "付款人与商户不在同一国家,或涉及两种货币。",
    "Individual lifecycle events replayed through the state machine.":
        "逐条经状态机重放的生命周期事件。",
    "Events the state machine refused as illegal for the state they arrived in. "
    "They never reached a ledger.":
        "状态机判定为对当前状态非法而拒绝的事件。它们从未进入任何账本。",
    "Money invariants that did not hold: FX, fees, authorisation gaps, double credits.":
        "未成立的资金恒等式:汇率、手续费、授权差额、重复入账。",
    "Risk operations": "风险运营",
    "Risk signals": "风险信号",
    "Cases opened": "开启案件",
    "Auto-released": "自动放行",
    "Routed to a person": "转人工",
    "Median handling": "处理时长中位数",
    "P90 handling": "处理时长 P90",
    "Fired by deterministic rules. No language model participates in detection.":
        "由确定性规则触发。检测环节没有任何语言模型参与。",
    "One per transaction the policy did not auto-release.":
        "策略未自动放行的每笔交易对应一个案件。",
    "Nothing fired above low severity and residual risk was under threshold. "
    "No human looked at these, and the policy recorded why.":
        "没有高于低严重度的信号触发,且残余风险低于阈值。无人查看这些交易,策略记录了原因。",
    "The manual review rate - the cost side of the detection trade-off.":
        "人工复核率——检测权衡中的成本侧。",
    "Simulated analyst handling time, opened to resolved.":
        "模拟分析师处理时长,从开启到处置。",
    "The tail is what breaks an operations team, not the median.":
        "压垮运营团队的是长尾,不是中位数。",
    "Handling times and every human decision behind them are **simulated** with a fixed error "
    "rate. They describe the simulation's parameters, not real reviewer behaviour.":
        "处理时长及其背后的每一个人工决策都是**模拟的**,采用固定错误率。"
        "它们描述的是模拟参数,不是真实审核员的行为。",
    "Volume and queue load": "交易量与队列压力",
    "Where the policy sends things": "策略把交易送去哪里",
    "`auto_hold` stops the payment immediately, and still opens a case: the money is "
    "safe by default, but the *outcome* is a person's to confirm.":
        "`auto_hold` 立即停止这笔支付,但仍然开启案件:资金默认是安全的,而*结论*要由人确认。",
    "Payment lifecycle": "支付生命周期",
    "Busiest cross-border corridors": "最繁忙的跨境通道",
    "Colour is the share of that corridor's payments that opened a case.":
        "颜色代表该通道中开启案件的支付占比。",
    "Which rules are doing the work": "哪些规则在真正起作用",
    "A low percentage is not automatically a bad rule. `R301_GEO_MISMATCH` is deliberately "
    "low-severity: most people paying from another country are on holiday, and it earns its place "
    "only in combination with something else.":
        "百分比低不等于规则不好。`R301_GEO_MISMATCH` 被刻意设为低严重度:"
        "大多数从异国付款的人只是在旅游,它只有与其他信号组合时才有价值。",
    "Feed health": "数据源健康度",
    "Events quarantined": "事件隔离率",
    "No device fingerprint": "缺设备指纹",
    "Illegal transitions the state machine refused.": "状态机拒绝的非法状态转移。",
    "These cannot be decided without asking someone.": "不向人索要材料就无法判定。",
    "Each break is a money invariant that failed, computed with integer and decimal "
    "arithmetic - never floating point. The rule engine reads these rows rather than "
    "recomputing the money, so a break always means exactly one thing.":
        "每条差异都是一个未成立的资金恒等式,用整数与十进制运算得出——绝不用浮点数。"
        "规则引擎读取这些记录而非重算金额,因此一条差异永远只有一种含义。",

    # --- Transaction Explorer -------------------------------------------
    "Transaction Explorer": "交易浏览器",
    "Every payment, its lifecycle, its money and the signals it produced.":
        "每一笔支付、它的生命周期、资金流向,以及它产生的信号。",
    "Search": "搜索",
    "transaction, wallet, merchant or idempotency key": "交易号、钱包、商户或幂等键",
    "Payment state": "支付状态",
    "Policy action": "策略动作",
    "Risk band": "风险等级",
    "Presentment currency": "计价币种",
    "Corridor": "通道",
    "Highest severity": "最高严重度",
    "Only with reconciliation breaks": "仅显示有对账差异的",
    "Select a row to open the full transaction record.": "选择一行以打开完整交易记录。",
    "Money": "资金",
    "FX": "汇率",
    "Context": "上下文",
    "Lifecycle": "生命周期",
    "Risk signals (detail)": "风险信号",
    "Reconciliation": "对账",
    "No rule fired on this transaction.": "没有规则在这笔交易上触发。",
    "The money reconciles.": "资金对账一致。",
    "Merchant free text": "商户自由文本",
    "Merchant-supplied text is attacker-controlled. It is screened before any model "
    "reads it; see the Case Detail page for what the copilot was actually shown.":
        "商户提交的文本是攻击者可控的。在任何模型读取之前都会先经过筛查;"
        "副驾驶实际看到的内容见「案件详情」页。",
    "This transaction received events the state machine refused. They were quarantined and "
    "never reached the ledger - the money below is still correct.":
        "这笔交易收到了状态机拒绝的事件。它们已被隔离且从未进入账本——下方金额仍然正确。",

    # --- Case Queue ------------------------------------------------------
    "Case Queue": "案件队列",
    "Every case the deterministic policy could not close on its own, with the reason it exists "
    "and the clock it is running against.":
        "确定性策略无法自行关闭的每一个案件,附带它存在的原因和它正在跑的时钟。",
    "Open cases": "待处理案件",
    "Critical + high": "严重 + 高危",
    "Past SLA": "超 SLA",
    "Awaiting information": "等待补充材料",
    "Appealed": "已申诉",
    "Overturned holds": "被推翻的拦截",
    "Not yet resolved.": "尚未处置。",
    "The part of the queue that cannot wait.": "队列中不能等的部分。",
    "SLA is set by risk band: 2h critical, 8h high, 24h medium, 72h low.":
        "SLA 按风险等级设定:严重 2 小时、高 8 小时、中 24 小时、低 72 小时。",
    "Blocked on a person, not on an analyst.": "卡在他人身上,而不是卡在分析师身上。",
    "Payers and merchants contesting a resolved case.": "付款人和商户对已处置案件提出异议。",
    "Holds an appeal proved wrong. This number existing at all is the point.":
        "被申诉证明是错误的拦截。这个数字本身存在就是意义所在。",
    "Queue shape": "队列构成",
    "SLA by risk band": "各风险等级的 SLA",
    "Handling times come from **simulated** analyst behaviour with a fixed error rate, not "
    "from observed human work.":
        "处理时长来自采用固定错误率的**模拟**分析师行为,不是观测到的真人工作。",
    "Case state": "案件状态",
    "Reason family": "原因族",
    "Owning role": "归属角色",
    "Scope": "范围",
    "Open only": "仅待处理",
    "All cases": "全部案件",
    "Breached SLA": "已超 SLA",
    "`AI suggests` is advisory and carries no authority. The column exists next to `Decided` on "
    "purpose: the gap between them is a number this product reports rather than hides.":
        "`AI 建议` 只是参考,不带任何权限。它被刻意放在 `人工结论` 旁边:"
        "两者之间的差距是本产品选择公开而非隐藏的一个指标。",
    "Outcomes and reason codes": "处置结果与理由码",
    "Appeals": "申诉",
    "No appeals in this dataset.": "本数据集中没有申诉。",
    "An accepted appeal closes the case as `closed_false_positive` - the only state that "
    "counts toward recovery. A wrong hold that nobody records is a wrong hold nobody fixes.":
        "申诉被接受会把案件关闭为 `closed_false_positive`——唯一计入误拦回收的状态。"
        "没人记录的错误拦截,就是没人会修的错误拦截。",

    # --- Case Detail -----------------------------------------------------
    "Case Detail": "案件详情",
    "Case": "案件",
    "Risk score": "风险分",
    "Signals": "信号数",
    "Amount": "金额",
    "SLA due": "SLA 到期",
    "**Why this case exists:**": "**这个案件为什么存在:**",
    "Evidence": "证据",
    "Payment timeline": "支付时间线",
    "Reconciliation breaks (detail)": "对账差异",
    "Residual-risk model": "残余风险模型",
    "Merchant free text — untrusted, attacker-controlled": "商户自由文本 — 不可信,攻击者可控",
    "AI investigation brief": "AI 调查简报",
    "Advisory only": "仅供参考",
    "This brief organises evidence, explains signals, names what is missing and "
    "<em>suggests</em> an action. It has no authority to release, hold, refund or close "
    "anything, and the audit log refuses to record an AI actor on a decision.":
        "本简报整理证据、解释信号、指出缺失材料,并<em>建议</em>一个动作。"
        "它没有放行、拦截、退款或结案的权限,审计日志也拒绝把 AI 记录为决策执行者。",
    "Regenerate brief": "重新生成简报",
    "No brief has been generated for this case yet.": "该案件尚未生成简报。",
    "Suggested action:": "建议动作:",
    "confidence": "置信度",
    "Summary": "摘要",
    "Key facts": "关键事实",
    "What the signals mean": "信号含义",
    "Conflicts in the evidence": "证据中的矛盾",
    "Missing information": "缺失信息",
    "Questions to ask": "应当追问的问题",
    "Guardrails and provenance": "护栏与溯源",
    "Decision": "决策",
    "Action": "动作",
    "Reason code": "理由码",
    "Note": "备注",
    "what settled it": "是什么决定了结论",
    "Your identifier": "你的标识",
    "Commit decision": "提交决策",
    "Decision history": "决策历史",
    "No decision has been committed on this case yet.": "该案件尚未提交任何决策。",
    "A case can be appealed once it has been resolved.": "案件处置后方可申诉。",
    "Claimant": "申诉方",
    "Evidence type": "证据类型",
    "File appeal": "提交申诉",
    "Accept appeal": "接受申诉",
    "Reject appeal": "驳回申诉",
    "**The copilot abstained.**": "**副驾驶选择弃权。**",

    # --- follow-up conversation -----------------------------------------
    "Ask a follow-up": "追问",
    "The brief answers the first question. This answers the second — and it gets a **wider** "
    "packet than the brief did: this wallet's and merchant's history, the payout group, and the "
    "decision trail. Same rules apply: every answer cites the fields it used, an answer that "
    "cannot be grounded is withheld rather than guessed, and **a question that asks the copilot "
    "to decide is refused, not answered.**":
        "简报回答第一个问题,这里回答第二个——并且它拿到的**上下文包更宽**:"
        "这个钱包和商户的历史、收款账户群组、决策轨迹。规则不变:"
        "每个回答都要引用它用到的字段;无法落地的回答会被扣下而不是猜;"
        "**要求副驾驶替你做决定的问题会被拒绝,而不是被回答。**",
    "Questions these packets can answer:": "这些上下文包能回答的问题:",
    "Ask about this wallet, this merchant, the money, or a signal…":
        "问问这个钱包、这个商户、资金,或者某个信号……",
    "asked by": "提问人",
    "refused": "已拒绝",
    "No answer could be grounded.": "没有可落地引用的答案。",
    "cites:": "引用:",
    "Free text on this wallet's or merchant's other transactions matched injection patterns "
    "and was withheld from the model before any question was asked.":
        "该钱包或商户其他交易上的自由文本匹配到了注入模式,在任何提问之前就已对模型屏蔽。",

    # --- Audit Log -------------------------------------------------------
    "Audit Log": "审计日志",
    "Append-only and hash-chained. Nothing here is ever updated or deleted.":
        "仅追加、哈希链式。这里的任何内容都不会被修改或删除。",
    "Audit entries": "审计条目",
    "Human decisions": "人工决策",
    "AI briefs": "AI 简报",
    "Decisions by an AI actor": "由 AI 提交的决策",
    "Distinct actors": "不同操作者",
    "Every consequential act.": "每一次有后果的操作。",
    "Committed outcomes with a reason code.": "带理由码的已提交结论。",
    "Advisory only.": "仅供参考。",
    "This must be zero. `audit.log.record_decision` refuses any AI actor.":
        "这个数必须是 0。`audit.log.record_decision` 拒绝任何 AI 操作者。",
    "People, the policy engine and the pipeline.": "人、策略引擎和数据流水线。",
    "No AI actor appears on any committed decision — enforced in code, not by convention.":
        "没有任何已提交的决策上出现 AI 操作者——这是代码强制的,不是约定俗成。",
    "An AI actor appears on a committed decision. That is a contract violation.":
        "已提交的决策上出现了 AI 操作者。这违反了契约。",
    "Where the copilot and the human disagreed": "副驾驶与人工的分歧",
    "Guardrail outcomes": "护栏结果",
    "The log": "日志",
    "Actor role": "角色",
    "Object": "对象",
    "Search summary or object id": "搜索摘要或对象 ID",
    "Export the filtered log as CSV": "导出筛选后的日志为 CSV",
    "Refresh history": "构建历史",
    "Every build records its seed and the taxonomy, rules and model versions that produced it. "
    "A metric without its versions is not reproducible.":
        "每次构建都记录它的随机种子,以及产生它的分类体系、规则和模型版本。"
        "没有版本的指标是不可复现的。",

    # --- Evaluation ------------------------------------------------------
    "Evaluation": "评测",
    "Evaluation and AI boundaries": "评测与 AI 边界",
    "Read this before reading any number": "在看任何数字之前先读这个",
    "Risk detection": "风险检测",
    "AI brief quality": "AI 简报质量",
    "Agent safety": "Agent 安全",
    "Money and lifecycle": "资金与生命周期",
    "Operations": "运营",
    "Recall": "召回率",
    "Precision": "精确率",
    "False-positive rate": "误报率",
    "Manual review rate": "人工复核率",
    "Auto-release leakage": "自动放行漏检率",
    "Per scenario": "按场景",
    "Per rule": "按规则",
    "Where the boundary sits": "边界在哪里",
    "Task": "任务",
    "Owner": "责任方",
    "Why": "原因",

    "Actionable transactions the policy routed to a person or held.":
        "策略转人工或拦截的、真正需要处理的交易。",
    "Of everything routed, how much really was actionable.":
        "所有被转出的交易中,真正需要处理的比例。",
    "The share of all traffic a person has to look at. This is the analyst-time bill.":
        "全部流量中需要人工查看的比例。这就是分析师的工时账单。",
    "Actionable traffic released with nobody looking. These are the misses that matter.":
        "无人查看就被放行的、本该处理的交易。这些才是要命的漏检。",
    "Payments stopped by the machine before a human read the case.":
        "在任何人读到案件之前就被机器停掉的支付。",
    "Benign payments stopped by the machine. This is the number that decides whether a "
    "threshold is shippable.":
        "被机器停掉的正常支付。这个数字决定一个阈值能不能上线。",
    "Every point is a real run of the decision policy at that auto-release threshold. "
    "The choice is not 'which is best' — it is how much analyst time this team has, and how "
    "much unlooked-at leakage the business will accept.":
        "每个点都是决策策略在该自动放行阈值下的一次真实运行。这不是「哪个最好」的选择——"
        "而是这个团队有多少分析师工时,以及业务能接受多少无人查看的漏检。",
    "This is the only screen where a product decision is made rather than a case decision.":
        "这是全站唯一一个做**产品决策**而非案件决策的页面。",
    "Benign payments the machine stopped before any person read the case. Recall and "
    "precision are aggregate statistics; this one is a count of people who could not pay "
    "for something. It is recoverable through the appeal flow, which is why the product has "
    "one — but a threshold that grows this number needs an argument, not a slider.":
        "在任何人读到案件之前就被机器停掉的正常支付。召回率和精确率是聚合统计;"
        "而这个数字是「有多少人付不了钱」。它可以通过申诉流程挽回——这正是产品设有申诉的原因——"
        "但让这个数字变大的阈值需要的是论证,不是拖一下滑块。",
    # --- Evaluation page ---
    "Of the transactions the generator labelled actionable, the share the policy routed "
    "anywhere other than auto-release.":
        "在生成器标记为「需要处理」的交易中,被策略转到自动放行以外任何去向的比例。",
    "Of the transactions routed to a person, the share that really were actionable.":
        "在转人工的交易中,真正需要处理的比例。",
    "Benign transactions routed to a person. This is the cost of the recall above.":
        "被转人工的正常交易。这是上面那个召回率的代价。",
    "The share of all traffic a person has to look at.": "全部流量中需要人工查看的比例。",
    "Actionable transactions that were auto-released - the misses that matter most.":
        "被自动放行的、本该处理的交易——最要命的那类漏检。",
    "Red bars should be near 100%; green bars are the false-positive cost. "
    "`impossible_travel` sits below the rest for a reason worth knowing: the *first* payment "
    "of an impossible hop carries no evidence until the second one arrives, so per-episode "
    "detection is higher than the per-transaction figure shown here.":
        "红色柱应接近 100%;绿色柱是误报成本。`impossible_travel` 明显偏低,原因值得知道:"
        "一次「不可能移动」的*第一笔*支付在第二笔到达之前不携带任何证据,"
        "因此按「事件」计的检出率高于这里按「单笔交易」计的数字。",

    # --- Policy Tuning ---------------------------------------------------
    "Policy Tuning": "策略调参",
    "Where the two automatic thresholds sit, and what each setting costs.":
        "两个自动化阈值设在哪里,以及每种设定的代价。",
    "Auto-release below": "低于此值自动放行",
    "Auto-hold at or above": "达到此值自动拦截",
    "shipped default:": "发布默认值:",
    "What this setting produces": "这个设定产生的结果",
    "Review rate": "复核率",
    "Leakage": "漏检",
    "Auto-holds": "自动拦截",
    "Wrong auto-holds": "错误的自动拦截",
    "The trade-off": "权衡",
    "Where the traffic goes": "交易流向",
    "The number to watch": "最该盯的数字",
    "Full curve": "完整曲线",
    "Against the shipped setting:": "相对发布设定:",
    "Identical outcome to the shipped setting.": "与发布设定结果一致。",
    "The knee of this curve is the argument to have with an operations lead: past it, each "
    "additional point of recall costs several points of analyst time. Below it, you are leaving "
    "cheap detection on the table.":
        "这条曲线的拐点就是你该和运营负责人争论的地方:越过它,每多一个百分点的召回率"
        "要花掉好几个百分点的分析师时间;在它下方,你则白白丢掉了廉价的检测收益。",
}


def current_language() -> str:
    """The active language, preferring the URL so a link carries it."""
    from_url = st.query_params.get("lang")
    if from_url in LANGUAGES:
        st.session_state["lang"] = from_url
    return st.session_state.get("lang", DEFAULT_LANGUAGE)


def t(text: str) -> str:
    """Translate, falling back to the English source text."""
    if current_language() == "zh":
        return ZH.get(text, text)
    return text


def language_toggle() -> None:
    """The switch, top-right of the content area.

    Streamlit has no real top-right slot, so this is a narrow trailing column at
    the very top of the page. Placing it in the sidebar would have been easier
    and would have hidden it on the one screen where somebody most needs it: the
    first one they open.
    """
    spacer, control = st.columns([6, 1])
    with control:
        chosen = st.segmented_control(
            t("Language"),
            options=list(LANGUAGES),
            format_func=lambda code: LANGUAGES[code],
            default=current_language(),
            key="_language_control",
            label_visibility="collapsed",
        )
    if chosen and chosen != st.session_state.get("lang"):
        st.session_state["lang"] = chosen
        st.query_params["lang"] = chosen
        st.rerun()
    del spacer


def translation_coverage() -> dict[str, int]:
    """How much of the interface actually has a Chinese string.

    Exposed so a test can assert it rather than anyone guessing.
    """
    return {"translated": len(ZH), "language_count": len(LANGUAGES)}
