"""Bilingual interface: English by default, Chinese one click away.

The design decision here is what the *key* is. Inventing keys (`overview.title`)
means every string has to be looked up in two places to be read, and a missing
key renders as `overview.title` in front of a user. So the English source text is
the key: `t("Overview")` returns the Chinese if there is one and the English if
there is not. A missing translation degrades to correct English rather than to a
placeholder, and the code stays readable in its own right.

Why this product needs it at all: the explanations *are* the argument. A screen
that says "26.9% routed to a person" in Chinese and then explains why that number
is the cost of the recall in English has translated the labels and left the
reasoning behind.

What is deliberately NOT translated:
  * identifiers - `CASE_0001121`, `R303_IMPOSSIBLE_TRAVEL`, `txn.captured_minor`;
  * currency codes and money;
  * generated content - rule details, AI briefs, audit summaries. These come from
    the pipeline and the model, not the interface, and machine-translating a
    signal's detail string would put a translation error inside evidence.
That last one is a limitation, stated on screen rather than hidden.
"""

from __future__ import annotations

import re

import streamlit as st

LANGUAGES = {"en": "English", "zh": "中文"}
DEFAULT_LANGUAGE = "en"

# English source text -> Chinese. Everything not in here falls back to English.
ZH: dict[str, str] = {
    # --- chrome and shared ---------------------------------------------
    "CrossBorder AML RiskOps": "CrossBorder AML RiskOps 跨境支付反洗钱平台",
    "Cross-border payment risk operations workbench": "跨境支付风险运营工作台",
    "Last build": "最近构建",
    "seed": "随机种子",
    "validation": "校验",
    "rules": "规则",
    "model": "模型",
    "taxonomy": "分类体系",
    "reporting cut-off": "报告截止日",
    "Language": "语言",
    "**AI boundary.** The copilot organises evidence and *recommends*. "
    "It cannot release, hold, refund or close anything. Those are committed by a person "
    "or by the deterministic policy, and the audit log refuses to record an AI actor on a "
    "decision.":
        "**AI 边界。** 副驾驶整理证据并*提出建议*。它不能放行、拦截、退款或结案——"
        "这些由人或确定性策略引擎提交,审计日志拒绝把 AI 记录为决策执行者。",
    "The warehouse has not been built yet. Run this once, then reload:":
        "数据仓库尚未构建。先运行一次,然后刷新页面:",
    "Interface language only. Rule details, AI briefs and audit entries are shown as the "
    "pipeline and the model produced them — translating evidence would put a translation "
    "error inside it.":
        "仅界面语言切换。规则明细、AI 简报和审计记录按流水线与模型生成的原文展示——"
        "翻译证据等于把翻译误差放进证据里。",

    # --- the synthetic-data banner -------------------------------------
    "Synthetic data · simulated environment.": "合成数据 · 模拟环境。",
    "Every transaction, merchant, wallet, device and risk label on this screen was generated by a "
    "seeded script. Nothing here has touched a real payment network, bank, merchant or customer, "
    "and no figure describes a real business outcome.":
        "本页面上的每一笔交易、商户、钱包、设备和风险标签都由固定随机种子的脚本生成。"
        "这里没有任何内容接触过真实支付网络、银行、商户或客户,也没有任何数字描述真实业务结果。",
    "Decisions taken on this screen are written to the local warehouse and are part of the demo.":
        "本页面上做出的决策会写入本地数据仓库,属于演示的一部分。",

    # --- navigation ------------------------------------------------------
    # Passed to st.Page in app/Home.py. These are the sidebar entries, which the
    # filename-based `pages/` directory could not translate at all.
    "Transaction Explorer": "交易浏览器",
    "Case Queue": "案件队列",
    "Case Detail": "案件详情",
    "Audit Log": "审计日志",
    "Evaluation": "评测",
    "Policy Tuning": "策略调参",

    # --- Overview -------------------------------------------------------
    "Overview": "总览",
    "One synthetic cross-border payment estate, the risk signals it produced, and the case "
    "queue that came out of it.":
        "一套合成的跨境支付资产、它产生的风险信号,以及由此形成的案件队列。",
    "Transactions": "交易笔数",
    "Cross-border": "跨境交易",
    "Payment events": "支付事件",
    "Quarantined events": "隔离事件",
    "Reconciliation breaks": "对账差异",
    "Every payment in the reporting window.": "报告窗口内的每一笔支付。",
    "Payer and merchant in different countries, or two currencies involved.":
        "付款人与商户不在同一国家,或涉及两种货币。",
    "Individual lifecycle events replayed through the state machine.":
        "逐条经状态机重放的生命周期事件。",
    "Events the state machine refused as illegal for the state they arrived in. "
    "They never reached a ledger.":
        "状态机判定为对当前状态非法而拒绝的事件。它们从未进入任何账本。",
    "Money invariants that did not hold: FX, fees, authorisation gaps, double credits.":
        "未成立的资金恒等式:汇率、手续费、授权差额、重复入账。",
    "Risk operations": "风险运营",
    "Risk signals": "风险信号",
    "Cases opened": "开启案件",
    "Auto-released": "自动放行",
    "Routed to a person": "转人工",
    "Median handling": "处理时长中位数",
    "P90 handling": "处理时长 P90",
    "Fired by deterministic rules. No language model participates in detection.":
        "由确定性规则触发。检测环节没有任何语言模型参与。",
    "One per transaction the policy did not auto-release.":
        "策略未自动放行的每笔交易对应一个案件。",
    "Nothing fired above low severity and residual risk was under threshold. "
    "No human looked at these, and the policy recorded why.":
        "没有高于低严重度的信号触发,且残余风险低于阈值。无人查看这些交易,策略记录了原因。",
    "The manual review rate - the cost side of the detection trade-off.":
        "人工复核率——检测权衡中的成本侧。",
    "Simulated analyst handling time, opened to resolved.":
        "模拟分析师处理时长,从开启到处置。",
    "The tail is what breaks an operations team, not the median.":
        "压垮运营团队的是长尾,不是中位数。",
    "Handling times and every human decision behind them are **simulated** with a fixed error "
    "rate. They describe the simulation's parameters, not real reviewer behaviour.":
        "处理时长及其背后的每一个人工决策都是**模拟的**,采用固定错误率。"
        "它们描述的是模拟参数,不是真实审核员的行为。",
    "Volume and queue load": "交易量与队列压力",
    "Where the policy sends things": "策略把交易送去哪里",
    "`auto_hold` stops the payment immediately, and still opens a case: the money is "
    "safe by default, but the *outcome* is a person's to confirm.":
        "`auto_hold` 立即停止这笔支付,但仍然开启案件:资金默认是安全的,而*结论*要由人确认。",
    "Payment lifecycle": "支付生命周期",
    "Busiest cross-border corridors": "最繁忙的跨境通道",
    "Colour is the share of that corridor's payments that opened a case.":
        "颜色代表该通道中开启案件的支付占比。",
    "Which rules are doing the work": "哪些规则在真正起作用",
    "A low percentage is not automatically a bad rule. `R301_GEO_MISMATCH` is deliberately "
    "low-severity: most people paying from another country are on holiday, and it earns its place "
    "only in combination with something else.":
        "百分比低不等于规则不好。`R301_GEO_MISMATCH` 被刻意设为低严重度:"
        "大多数从异国付款的人只是在旅游,它只有与其他信号组合时才有价值。",
    "Feed health": "数据源健康度",
    "Events quarantined": "事件隔离率",
    "No device fingerprint": "缺设备指纹",
    "Illegal transitions the state machine refused.": "状态机拒绝的非法状态转移。",
    "These cannot be decided without asking someone.": "不向人索要材料就无法判定。",
    "Each break is a money invariant that failed, computed with integer and decimal "
    "arithmetic - never floating point. The rule engine reads these rows rather than "
    "recomputing the money, so a break always means exactly one thing.":
        "每条差异都是一个未成立的资金恒等式,用整数与十进制运算得出——绝不用浮点数。"
        "规则引擎读取这些记录而非重算金额,因此一条差异永远只有一种含义。",

    # --- Transaction Explorer -------------------------------------------
    "Every payment, its lifecycle, its money and the signals it produced.":
        "每一笔支付、它的生命周期、资金流向,以及它产生的信号。",
    "Search": "搜索",
    "transaction, wallet, merchant or idempotency key": "交易号、钱包、商户或幂等键",
    "Payment state": "支付状态",
    "Policy action": "策略动作",
    "Risk band": "风险等级",
    "Presentment currency": "计价币种",
    "Corridor": "通道",
    "Highest severity": "最高严重度",
    "Only with reconciliation breaks": "仅显示有对账差异的",
    "Select a row to open the full transaction record.": "选择一行以打开完整交易记录。",
    "Money": "资金",
    "FX": "汇率",
    "Context": "上下文",
    "Lifecycle": "生命周期",
    "Risk signals (detail)": "风险信号",
    "Reconciliation": "对账",
    "No rule fired on this transaction.": "没有规则在这笔交易上触发。",
    "The money reconciles.": "资金对账一致。",
    "Merchant free text": "商户自由文本",
    "Merchant-supplied text is attacker-controlled. It is screened before any model "
    "reads it; see the Case Detail page for what the copilot was actually shown.":
        "商户提交的文本是攻击者可控的。在任何模型读取之前都会先经过筛查;"
        "副驾驶实际看到的内容见「案件详情」页。",
    "This transaction received events the state machine refused. They were quarantined and "
    "never reached the ledger - the money below is still correct.":
        "这笔交易收到了状态机拒绝的事件。它们已被隔离且从未进入账本——下方金额仍然正确。",

    # --- Case Queue ------------------------------------------------------
    "Every case the deterministic policy could not close on its own, with the reason it exists "
    "and the clock it is running against.":
        "确定性策略无法自行关闭的每一个案件,附带它存在的原因和它正在跑的时钟。",
    "Open cases": "待处理案件",
    "Critical + high": "严重 + 高危",
    "Past SLA": "超 SLA",
    "Awaiting information": "等待补充材料",
    "Appealed": "已申诉",
    "Overturned holds": "被推翻的拦截",
    "Not yet resolved.": "尚未处置。",
    "The part of the queue that cannot wait.": "队列中不能等的部分。",
    "SLA is set by risk band: 2h critical, 8h high, 24h medium, 72h low.":
        "SLA 按风险等级设定:严重 2 小时、高 8 小时、中 24 小时、低 72 小时。",
    "Blocked on a person, not on an analyst.": "卡在他人身上,而不是卡在分析师身上。",
    "Payers and merchants contesting a resolved case.": "付款人和商户对已处置案件提出异议。",
    "Holds an appeal proved wrong. This number existing at all is the point.":
        "被申诉证明是错误的拦截。这个数字本身存在就是意义所在。",
    "Queue shape": "队列构成",
    "SLA by risk band": "各风险等级的 SLA",
    "Handling times come from **simulated** analyst behaviour with a fixed error rate, not "
    "from observed human work.":
        "处理时长来自采用固定错误率的**模拟** 分析师行为,不是观测到的真人工作。",
    "Case state": "案件状态",
    "Reason family": "原因族",
    "Owning role": "归属角色",
    "Scope": "范围",
    "Open only": "仅待处理",
    "All cases": "全部案件",
    "Breached SLA": "已超 SLA",
    "`AI suggests` is advisory and carries no authority. The column exists next to `Decided` on "
    "purpose: the gap between them is a number this product reports rather than hides.":
        "`AI 建议` 只是参考,不带任何权限。它被刻意放在 `人工结论` 旁边:"
        "两者之间的差距是本产品选择公开而非隐藏的一个指标。",
    "Outcomes and reason codes": "处置结果与理由码",
    "Appeals": "申诉",
    "No appeals in this dataset.": "本数据集中没有申诉。",
    "An accepted appeal closes the case as `closed_false_positive` - the only state that "
    "counts toward recovery. A wrong hold that nobody records is a wrong hold nobody fixes.":
        "申诉被接受会把案件关闭为 `closed_false_positive`——唯一计入误拦回收的状态。"
        "没人记录的错误拦截,就是没人会修的错误拦截。",

    # --- Case Detail -----------------------------------------------------
    "Case": "案件",
    "Risk score": "风险分",
    "Signals": "信号数",
    "Amount": "金额",
    "SLA due": "SLA 到期",
    "**Why this case exists:**": "**这个案件为什么存在:**",
    "Evidence": "证据",
    "Payment timeline": "支付时间线",
    "Reconciliation breaks (detail)": "对账差异",
    "Residual-risk model": "残余风险模型",
    "Merchant free text — untrusted, attacker-controlled": "商户自由文本 — 不可信,攻击者可控",
    "AI investigation brief": "AI 调查简报",
    "Advisory only": "仅供参考",
    "This brief organises evidence, explains signals, names what is missing and "
    "<em>suggests</em> an action. It has no authority to release, hold, refund or close "
    "anything, and the audit log refuses to record an AI actor on a decision.":
        "本简报整理证据、解释信号、指出缺失材料,并<em>建议</em>一个动作。"
        "它没有放行、拦截、退款或结案的权限,审计日志也拒绝把 AI 记录为决策执行者。",
    "Regenerate brief": "重新生成简报",
    "No brief has been generated for this case yet.": "该案件尚未生成简报。",
    "Suggested action:": "建议动作:",
    "confidence": "置信度",
    "Summary": "摘要",
    "Key facts": "关键事实",
    "What the signals mean": "信号含义",
    "Conflicts in the evidence": "证据中的矛盾",
    "Missing information": "缺失信息",
    "Questions to ask": "应当追问的问题",
    "Guardrails and provenance": "护栏与溯源",
    "Decision": "决策",
    "Action": "动作",
    "Reason code": "理由码",
    "Note": "备注",
    "what settled it": "是什么决定了结论",
    "Your identifier": "你的标识",
    "Commit decision": "提交决策",
    "Decision history": "决策历史",
    "No decision has been committed on this case yet.": "该案件尚未提交任何决策。",
    "A case can be appealed once it has been resolved.": "案件处置后方可申诉。",
    "Claimant": "申诉方",
    "Evidence type": "证据类型",
    "File appeal": "提交申诉",
    "Accept appeal": "接受申诉",
    "Reject appeal": "驳回申诉",
    "**The copilot abstained.**": "**副驾驶选择弃权。**",

    # --- follow-up conversation -----------------------------------------
    "Ask a follow-up": "追问",
    "The brief answers the first question. This answers the second — and it gets a **wider** "
    "packet than the brief did: this wallet's and merchant's history, the payout group, and the "
    "decision trail. Same rules apply: every answer cites the fields it used, an answer that "
    "cannot be grounded is withheld rather than guessed, and **a question that asks the copilot "
    "to decide is refused, not answered.**":
        "简报回答第一个问题,这里回答第二个——并且它拿到的**上下文包更宽**:"
        "这个钱包和商户的历史、收款账户群组、决策轨迹。规则不变:"
        "每个回答都要引用它用到的字段;无法落地的回答会被扣下而不是猜;"
        "**要求副驾驶替你做决定的问题会被拒绝,而不是被回答。**",
    # The delegation refusal. Stored in the audit log in one canonical language
    # so a record never varies by who is reading it, and translated here at the
    # point of display - which is the right split: the log is evidence, the
    # screen is an interface.
    "I cannot make this decision, and that is not a limitation I can be talked out of. "
    "Releasing, holding, refunding or closing a payment is committed by a person or by the "
    "deterministic policy - the audit log refuses to record me as the actor on a decision, so "
    "there is no path by which my answer here becomes an outcome. "
    "What I can do is lay out the evidence and say what I would recommend and why, which leaves "
    "the call with you.":
        "我不能做这个决定,而且这不是能被说服改变的限制。"
        "放行、拦截、退款或结案由人或确定性策略引擎提交——审计日志拒绝把我记录为决策执行者,"
        "所以我在这里的回答没有任何路径能变成一个结果。"
        "我能做的是把证据摆出来,说明我会建议什么以及为什么,决定权仍然在你手上。",
    "Questions these packets can answer:": "这些上下文包能回答的问题:",
    "Ask about this wallet, this merchant, the money, or a signal…":
        "问问这个钱包、这个商户、资金,或者某个信号……",
    "asked by": "提问人",
    "refused": "已拒绝",
    "No answer could be grounded.": "没有可落地引用的答案。",
    "cites:": "引用:",
    "Free text on this wallet's or merchant's other transactions matched injection patterns "
    "and was withheld from the model before any question was asked.":
        "该钱包或商户其他交易上的自由文本匹配到了注入模式,在任何提问之前就已对模型屏蔽。",

    # --- Audit Log -------------------------------------------------------
    "Append-only and hash-chained. Nothing here is ever updated or deleted.":
        "仅追加、哈希链式。这里的任何内容都不会被修改或删除。",
    "Audit entries": "审计条目",
    "Human decisions": "人工决策",
    "AI briefs": "AI 简报",
    "Decisions by an AI actor": "由 AI 提交的决策",
    "Distinct actors": "不同操作者",
    "Every consequential act.": "每一次有后果的操作。",
    "Committed outcomes with a reason code.": "带理由码的已提交结论。",
    "Advisory only.": "仅供参考。",
    "This must be zero. `audit.log.record_decision` refuses any AI actor.":
        "这个数必须是 0。`audit.log.record_decision` 拒绝任何 AI 操作者。",
    "People, the policy engine and the pipeline.": "人、策略引擎和数据流水线。",
    "No AI actor appears on any committed decision — enforced in code, not by convention.":
        "没有任何已提交的决策上出现 AI 操作者——这是代码强制的,不是约定俗成。",
    "An AI actor appears on a committed decision. That is a contract violation.":
        "已提交的决策上出现了 AI 操作者。这违反了契约。",
    "Where the copilot and the human disagreed": "副驾驶与人工的分歧",
    "Guardrail outcomes": "护栏结果",
    "The log": "日志",
    "Actor role": "角色",
    "Object": "对象",
    "Search summary or object id": "搜索摘要或对象 ID",
    "Export the filtered log as CSV": "导出筛选后的日志为 CSV",
    "Refresh history": "构建历史",
    "Every build records its seed and the taxonomy, rules and model versions that produced it. "
    "A metric without its versions is not reproducible.":
        "每次构建都记录它的随机种子,以及产生它的分类体系、规则和模型版本。"
        "没有版本的指标是不可复现的。",

    # --- Evaluation ------------------------------------------------------
    "Evaluation and AI boundaries": "评测与 AI 边界",
    "Read this before reading any number": "在看任何数字之前先读这个",
    "Risk detection": "风险检测",
    "AI brief quality": "AI 简报质量",
    "Agent safety": "Agent 安全",
    "Money and lifecycle": "资金与生命周期",
    "Operations": "运营",
    "Recall": "召回率",
    "Precision": "精确率",
    "False-positive rate": "误报率",
    "Manual review rate": "人工复核率",
    "Auto-release leakage": "自动放行漏检率",
    "Per scenario": "按场景",
    "Per rule": "按规则",
    "Where the boundary sits": "边界在哪里",
    "Task": "任务",
    "Owner": "责任方",
    "Why": "原因",

    "Actionable transactions the policy routed to a person or held.":
        "策略转人工或拦截的、真正需要处理的交易。",
    "Of everything routed, how much really was actionable.":
        "所有被转出的交易中,真正需要处理的比例。",
    "The share of all traffic a person has to look at. This is the analyst-time bill.":
        "全部流量中需要人工查看的比例。这就是分析师的工时账单。",
    "Actionable traffic released with nobody looking. These are the misses that matter.":
        "无人查看就被放行的、本该处理的交易。这些才是要命的漏检。",
    "Payments stopped by the machine before a human read the case.":
        "在任何人读到案件之前就被机器停掉的支付。",
    "Benign payments stopped by the machine. This is the number that decides whether a "
    "threshold is shippable.":
        "被机器停掉的正常支付。这个数字决定一个阈值能不能上线。",
    "Every point is a real run of the decision policy at that auto-release threshold. "
    "The choice is not 'which is best' — it is how much analyst time this team has, and how "
    "much unlooked-at leakage the business will accept.":
        "每个点都是决策策略在该自动放行阈值下的一次真实运行。这不是「哪个最好」的选择——"
        "而是这个团队有多少分析师工时,以及业务能接受多少无人查看的漏检。",
    "This is the only screen where a product decision is made rather than a case decision.":
        "这是全站唯一一个做**产品决策** 而非案件决策的页面。",
    "Benign payments the machine stopped before any person read the case. Recall and "
    "precision are aggregate statistics; this one is a count of people who could not pay "
    "for something. It is recoverable through the appeal flow, which is why the product has "
    "one — but a threshold that grows this number needs an argument, not a slider.":
        "在任何人读到案件之前就被机器停掉的正常支付。召回率和精确率是聚合统计;"
        "而这个数字是「有多少人付不了钱」。它可以通过申诉流程挽回——这正是产品设有申诉的原因——"
        "但让这个数字变大的阈值需要的是论证,不是拖一下滑块。",
    # --- Evaluation page ---
    "Of the transactions the generator labelled actionable, the share the policy routed "
    "anywhere other than auto-release.":
        "在生成器标记为「需要处理」的交易中,被策略转到自动放行以外任何去向的比例。",
    "Of the transactions routed to a person, the share that really were actionable.":
        "在转人工的交易中,真正需要处理的比例。",
    "Benign transactions routed to a person. This is the cost of the recall above.":
        "被转人工的正常交易。这是上面那个召回率的代价。",
    "The share of all traffic a person has to look at.": "全部流量中需要人工查看的比例。",
    "Actionable transactions that were auto-released - the misses that matter most.":
        "被自动放行的、本该处理的交易——最要命的那类漏检。",
    "Red bars should be near 100%; green bars are the false-positive cost. "
    "`impossible_travel` sits below the rest for a reason worth knowing: the *first* payment "
    "of an impossible hop carries no evidence until the second one arrives, so per-episode "
    "detection is higher than the per-transaction figure shown here.":
        "红色柱应接近 100%;绿色柱是误报成本。`impossible_travel` 明显偏低,原因值得知道:"
        "一次「不可能移动」的*第一笔*支付在第二笔到达之前不携带任何证据,"
        "因此按「事件」计的检出率高于这里按「单笔交易」计的数字。",

    # --- Policy Tuning ---------------------------------------------------
    "Where the two automatic thresholds sit, and what each setting costs.":
        "两个自动化阈值设在哪里,以及每种设定的代价。",
    "Auto-release below": "低于此值自动放行",
    "Auto-hold at or above": "达到此值自动拦截",
    "shipped default:": "发布默认值:",
    "What this setting produces": "这个设定产生的结果",
    "Review rate": "复核率",
    "Leakage": "漏检",
    "Auto-holds": "自动拦截",
    "Wrong auto-holds": "错误的自动拦截",
    "The trade-off": "权衡",
    "Where the traffic goes": "交易流向",
    "The number to watch": "最该盯的数字",
    "Full curve": "完整曲线",
    "Against the shipped setting:": "相对发布设定:",
    "Identical outcome to the shipped setting.": "与发布设定结果一致。",
    "The knee of this curve is the argument to have with an operations lead: past it, each "
    "additional point of recall costs several points of analyst time. Below it, you are leaving "
    "cheap detection on the table.":
        "这条曲线的拐点就是你该和运营负责人争论的地方:越过它,每多一个百分点的召回率"
        "要花掉好几个百分点的分析师时间;在它下方,你则白白丢掉了廉价的检测收益。",
}


def current_language() -> str:
    """The active language, preferring the URL so a link carries it."""
    from_url = st.query_params.get("lang")
    if from_url in LANGUAGES:
        st.session_state["lang"] = from_url
    return st.session_state.get("lang", DEFAULT_LANGUAGE)


def t(text: str) -> str:
    """Translate, falling back to the English source text."""
    if current_language() == "zh":
        return ZH.get(text, text)
    return text


# --------------------------------------------------------------------------- #
# The cross-border AML layer
#
# Kept as its own table rather than merged into ZH above, so it is obvious which
# strings belong to which product surface when either one changes. Merged into
# ZH at import time, so `t()` needs no special case.
#
# Two translation choices worth stating, because both recur:
#
# "typology" is 典型学 rather than 类型 - it is the AML term of art for a named
# pattern of behaviour, and 类型 would read as a generic category.
#
# The disposition and case-state keys (close_no_action, awaiting_information...)
# are translated for display but the stored value stays English. The audit log
# and the database hold the English key; only the label a person reads changes.
# --------------------------------------------------------------------------- #

ZH_AML: dict[str, str] = {
    # -- page titles and navigation --
    "Cross-border AML": "跨境反洗钱",
    "Payment risk operations": "支付风险运营",
    "Evidence and evaluation": "证据与评测",
    "AML Operations": "反洗钱运营",
    "AML Alert Queue": "反洗钱预警队列",
    "Investigation Workbench": "调查工作台",
    "AML Operations Overview": "反洗钱运营总览",

    # -- alert queue --
    "Alerts grouped into cases, ordered by investigation priority, and cut at the review "
    "capacity a team of this size actually has.":
        "预警聚合为案件,按调查优先级排序,并按这个规模的团队真实拥有的复核容量切分。",
    "**A case below the capacity line has not been cleared.** It has not been reviewed. "
    "Some of them contain patterns the evaluation counts as missed for exactly this reason, "
    "and that number is reported rather than hidden.":
        "**容量线以下的案件不等于已排除风险。** 它只是没有被人看过。其中一部分确实包含被注入的模式,"
        "评测正是据此把它们计为漏检——这个数字是报出来的,不是藏起来的。",
    "The queue": "队列",
    "Open a case in the Investigation Workbench to see its evidence, what argues against it, "
    "and what is missing.":
        "在调查工作台打开案件,可以看到它的证据、反证,以及缺失了什么。",
    "Priority bands": "优先级分档",
    "Band cuts were calibrated against this seeded dataset, not taken from anywhere external. "
    "A different population would need them re-cut.":
        "分档阈值是对着这份固定种子的数据标定出来的,不是从任何外部标准取来的。换一批数据就需要重新标定。",
    "Which typologies raised the alerts": "预警来自哪些典型学",
    "A case can carry more than one typology. Several independent typologies on one account "
    "is the strongest thing this system is able to say.":
        "一个案件可以承载多条典型学。同一账户上出现多条相互独立的典型学,是这套系统能给出的最强论断。",
    "Priority band": "优先级档位",
    "Show": "显示",
    "Account or case id": "账户或案件编号",
    "#": "序",
    "Account": "账户",
    "Priority": "优先级",
    "Band": "档位",
    "Typologies": "典型学",
    "Alerts": "预警",
    "Transfers": "转账",
    "Amount (USD)": "金额(美元)",
    "State": "状态",
    "In capacity": "在容量内",
    "The AML layer has not been built yet. Run this once, then reload:":
        "反洗钱层尚未构建。执行一次下面的命令,然后刷新:",
    "After duplicates were collapsed. Each one names the transfers it rests on.":
        "已合并重复项。每条预警都写明了它依据的转账。",
    "Cases": "案件",
    "An alert is not a case. A case is one subject over one window.":
        "预警不等于案件。一个案件是一个主体在一个时间窗内的完整故事。",
    "Within review capacity": "复核容量内",
    "What a team of this size could open. Everything else waits.":
        "这个规模的团队今天能打开的数量。其余的排队等待。",
    "Backlog": "积压",
    "Not cleared and not low-risk — simply not looked at yet.":
        "不是已排除,也不是低风险——只是还没有人看。",
    "Showing {shown} of {total} cases.": "显示 {shown} 条,共 {total} 条案件。",
    "Within capacity": "容量内",

    # -- workbench --
    "Why these alerts were treated as one case:": "这些预警为什么被当作同一个案件:",
    "Why this case is where it is in the queue": "这个案件为什么排在这个位置",
    "Priority is an ordering, not a verdict. It answers 'which case should a person open "
    "next', and says nothing about whether anything wrong happened here.":
        "优先级是排序,不是结论。它回答的是「接下来应该先看哪一个」,"
        "对这里是否真的发生了什么不作任何判断。",
    "Customer and account": "客户与账户",
    "What was found, and what would argue against it": "发现了什么,以及有什么会推翻它",
    "Cross-border transfer timeline": "跨境转账时间线",
    "Who this account moved money with": "这个账户与谁之间有资金往来",
    "What we cannot see": "我们看不到的部分",
    "A gap is a reason to request information, not on its own a reason to escalate. Missing "
    "data is very often a defect at the sending institution.":
        "信息缺失是补充材料的理由,本身不构成升级处理的理由。数据缺失往往是汇出机构的操作缺陷。",
    "Record an investigation decision": "记录调查结论",
    "This system organises evidence and orders a queue. It does not decide. It cannot freeze "
    "an account, block a payment, file anything with any authority, or conclude that money "
    "was laundered — no such action exists in the code, not merely in the interface.":
        "这套系统整理证据、排列队列,它不做决定。它不能冻结账户、拦截支付、向任何机构提交任何东西,"
        "也不能认定发生了洗钱——这些动作在代码里根本不存在,而不只是界面上没有按钮。",
    "Claiming a case starts the SLA clock without recording an outcome — use it when you "
    "begin work, so a case correctly left open awaiting information is not measured as slow.":
        "认领案件只启动时效计时,不记录任何结论。开始工作时点它,这样一个正确地挂起等待材料的案件"
        "不会被计成处理缓慢。",
    "Claim this case": "认领此案件",
    "Case summary": "案件摘要",
    "This case sits below today's review capacity line. It is not cleared and not low-risk; "
    "nobody has opened it.":
        "这个案件落在今天的复核容量线以下。它不是已排除、也不是低风险——只是还没有人打开过。",
    "Beneficial owners on file": "在册实际受益人",
    "No beneficial owners recorded. For an individual customer that is expected; for a "
    "business it is itself a gap.":
        "没有登记实际受益人。个人客户属正常;企业客户则本身就是一处缺口。",
    "No transfers resolved for this case.": "该案件没有可解析的转账。",
    "No counterparties to show.": "没有可展示的交易对手。",
    "At least one beneficial owner on this customer is unverified.":
        "该客户至少有一名实际受益人未经核实。",
    "This is a business customer with no beneficial owner recorded.":
        "这是一个未登记任何实际受益人的企业客户。",
    "No structural information gap was detected on this case.":
        "该案件未检出结构性的信息缺口。",
    "Reason (required)": "理由(必填)",
    "Working notes (optional)": "工作备注(选填)",
    "Alerts this decision rests on": "本结论所依据的预警",
    "Record decision": "记录结论",
    "Decisions already recorded on this case": "该案件已记录的结论",
    "Your role": "你的角色",
    "Disposition": "处置",
    "What did you conclude, and from what? Name a transfer, an account, a typology or a "
    "document.":
        "你的结论是什么,依据是什么?请写明具体的转账、账户、典型学或文件。",
    "Case claimed.": "案件已认领。",
    "Priority band colours": "优先级档位配色",
    "Queue position {n}": "队列第 {n} 位",
    "What it read": "它读到了什么",
    "Value": "取值",
    "Owner reference": "受益人标识",
    "Ownership %": "持股比例 %",
    "Verification": "核实状态",
    "An unusual transaction is not a laundered transaction. These are the ordinary "
    "explanations to rule out before treating the pattern as a finding.":
        "异常交易不等于洗钱交易。在把这个模式当作结论之前,先排除下面这些寻常解释。",
    "outbound": "转出",
    "inbound": "转入",
    "Transfer": "转账",
    "When": "时间",
    "From": "付款方",
    "To": "收款方",
    "Currency": "币种",
    "USD": "美元",
    "Purpose": "用途",
    "Channel": "通道",
    "Beneficiary info": "收款人信息",
    "Counterparty account": "对手账户",
    "Direction": "方向",
    "Country": "国家/地区",
    "account": "账户",
    "customer": "客户",
    "transfers": "笔转账",
    "sent to": "转出至",
    "received from": "收自",
    "{n} device(s) appear across more than one counterparty in this case. A shared device is "
    "a link worth checking, and also the ordinary result of a family or an agent using one "
    "terminal.":
        "本案中有 {n} 台设备出现在不止一个交易对手上。共用设备是值得核查的关联,"
        "但也可能只是一家人或一个代理点共用一台终端。",
    "{n} of {total} transfers carry incomplete beneficiary information.":
        "{total} 笔转账中有 {n} 笔收款人信息不完整。",
    "{n} transfers declare no purpose at all.": "有 {n} 笔转账完全没有申报用途。",
    "Reason": "理由",
    "Factor": "因子",
    "Points": "得分",
    "Max weight": "权重上限",
    "Field": "字段",
    "Rule": "规则",
    "version": "版本",
    "Thresholds": "阈值",
    "Measured": "实测",
    "What would argue against this": "有什么会推翻这一点",
    "Recorded. The case moved to {state}, and the decision, its reason and your identifier "
    "are now in the hash-chained audit log.":
        "已记录。案件已转为「{state}」,结论、理由与你的标识已写入哈希链式审计日志。",
    "Customer": "客户",
    "Type": "类型",
    "Home country": "归属国家/地区",
    "Industry": "行业",
    "Onboarding risk level": "开户风险等级",
    "Expected monthly volume (USD)": "申报月交易量(美元)",
    "Profile last reviewed": "画像上次复核",
    "Account country": "账户国家/地区",
    "Opened": "开户时间",
    "Account age (days)": "账龄(天)",
    "Account type": "账户类型",
    "This alert absorbed {n} duplicate firing(s) of the same finding.":
        "该预警合并了同一发现的 {n} 次重复触发。",
    "By": "操作人",
    "Role": "角色",

    # -- operations overview --
    "Cross-border transfer volume, the alerts it produced, what aggregation did to them, and "
    "how much of the result a team of this size can actually work.":
        "跨境转账量、由此产生的预警、聚合对它们做了什么,"
        "以及这个规模的团队实际能处理其中多少。",
    "From alerts to a workable queue": "从预警到一个能干活的队列",
    "The number that matters operationally is not how many alerts fired, but how many "
    "separate things a person has to open.":
        "运营上真正重要的不是触发了多少条预警,而是一个人要分别打开多少个东西。",
    "Duplicate reduction": "重复消减",
    "Alerts per case": "每案件预警数",
    "Multi-typology cases": "多典型学案件",
    "Where the money moves": "资金流向",
    "What is aging": "哪些正在变老",
    "A case opens when its most recent alert fired, not when the batch ran. Queue-waiting "
    "time is one of the eight factors in investigation priority, so an old case eventually "
    "rises whatever else it scores.":
        "案件的开启时间是它最后一条预警触发的时刻,不是批处理运行的时刻。"
        "排队时长是调查优先级八个因子之一,所以无论其他项得分如何,旧案件最终都会浮上来。",
    "Share of raw firings that were repeats of a finding already reported.":
        "原始触发中属于「已报告发现的重复」的比例。",
    "1.00 would mean aggregation did nothing.": "等于 1.00 说明聚合什么也没做。",
    "Cases where independent typologies corroborate each other.":
        "多条相互独立的典型学彼此印证的案件。",
    "Alerts by typology": "各典型学的预警数",
    "A rule producing most of the volume is not necessarily the most useful rule — check it "
    "against per-typology recall in the evaluation before tuning it.":
        "产生最多量的规则未必是最有用的规则——调阈值之前,先对照评测里的分典型学召回率看一眼。",
    "Corridors": "走廊",
    "Channels": "通道",
    "Currencies": "币种",
    "Alert rate by corridor": "各走廊预警率",
    "The agent cash-in channel carries more incomplete beneficiary data by construction, "
    "which is why the missing-information typology names the channel as counter-evidence.":
        "代理现金存入通道按设计就携带更多不完整的收款人信息,"
        "这正是「信息缺失」典型学把通道列为反证的原因。",
    "Amounts are compared on one normalised USD scale throughout, never on the presentment "
    "amount — otherwise a JPY transfer looks a hundred times larger than an equivalent USD "
    "one.":
        "金额全程在统一的美元标准化口径上比较,绝不使用原始交易币种金额——"
        "否则一笔日元转账看起来会比等值美元大一百倍。",
    "Corridors with fewer than 30 transfers are excluded: a 100% alert rate over two "
    "transfers is noise, and showing it would invite a conclusion about a country.":
        "转账少于 30 笔的走廊被排除:两笔转账上的 100% 预警率是噪声,"
        "展示它会诱导读者对某个国家得出结论。",
    "Synthetic cross-border remittances generated from a fixed seed.":
        "由固定随机种子生成的合成跨境汇款。",
    "Payer and beneficiary accounts in different countries.":
        "付款账户与收款账户位于不同国家/地区。",
    "After duplicate firings were collapsed.": "已合并重复触发。",
    "Alerts grouped by subject and window.": "按主体与时间窗聚合后的预警。",
    "Not yet dispositioned.": "尚未作出处置。",
    "Review capacity": "复核容量",
    "How many a team of this size could open. The rest is backlog.":
        "这个规模的团队能打开多少。其余的都是积压。",
    "Unreviewed — not cleared, and not judged low-risk.":
        "未复核——既不是已排除,也没有被判定为低风险。",
    "Decisions recorded": "已记录结论",
    "Every one by a named person with a written reason.":
        "每一条都由具名的人作出,并附书面理由。",
    "Raw alert firings": "原始预警触发",
    "After duplicate collapse": "去重之后",
    "After grouping into cases": "聚合为案件之后",
    "under a day": "不到一天",
    "1–7 days": "1–7 天",
    "8–30 days": "8–30 天",
    "over 30 days": "超过 30 天",
    "In an alert": "命中预警",
    "Alert rate": "预警率",

    "Contribution to the priority score": "对优先级得分的贡献",

    # -- the eight investigation-priority factors --
    # Rendered through `parse_contributions`, so they reach t() as data rather
    # than as literals. test_i18n asserts the table covers all eight.
    "Signal strength": "信号强度",
    "Corroborating typologies": "相互印证的典型学",
    "Amount involved": "涉及金额",
    "Movement speed": "资金速度",
    "Network breadth": "关系网络广度",
    "Missing information": "缺失信息",
    "Customer risk history": "客户风险历史",
    "Time waiting in queue": "排队等待时长",

    # -- the six typologies --
    "Structured transfers below a reporting threshold": "拆分至申报阈值以下的转账",
    "Were several transfers sized to stay under a threshold rather than sized by need?":
        "这几笔转账的金额,是按需要定的,还是为了压在阈值以下定的?",
    "A payroll, rent or instalment schedule can produce similar amounts on a regular cadence.":
        "工资、房租或分期付款计划本来就会按固定节奏产生金额相近的转账。",
    "Per-transfer limits set by the customer's own bank or the channel can cap amounts "
    "without any intent to avoid a threshold.":
        "客户自己银行或通道设定的单笔限额,会在毫无规避意图的情况下压低每笔金额。",
    "Check whether the same pattern is present in the months before the alert window; a "
    "long-standing habit is weaker evidence than a new one.":
        "查一下预警窗口之前几个月是否也是同样的模式;长期习惯远比新出现的行为证据力弱。",
    "Funds forwarded cross-border shortly after arriving": "资金到账后短时间内跨境转出",
    "Did this account hold the money, or only pass it on?":
        "这个账户是持有了这笔钱,还是只是过了一下手?",
    "Treasury sweeps, supplier settlement and payroll runs are all fast by design.":
        "资金归集、供应商结算和工资发放,本来就设计成快速完成。",
    "A named, consistent counterparty on both legs is a weaker signal than a new one.":
        "两端都是有名有姓、长期稳定的交易对手,信号强度远低于新出现的对手。",
    "Check whether the customer's declared business makes same-day forwarding normal.":
        "查一下客户申报的经营范围是否本来就会当天转出。",
    "Many unrelated senders converging on one account": "多个无关联付款方汇向同一账户",
    "Why are these particular senders all paying the same account?":
        "为什么偏偏是这些付款方都在付给同一个账户?",
    "Merchants, marketplaces, schools and landlords are all legitimately many-to-one.":
        "商户、平台、学校和房东本来就是合法的「多对一」。",
    "Check the declared business: a collection account for a real business explains the "
    "shape.":
        "查一下申报的经营范围:真实业务的归集账户就能解释这个形状。",
    "Remittance corridors concentrate by nature - many senders in one country paying one "
    "family account is ordinary.":
        "汇款走廊天然就是集中的——一个国家的许多汇款人打给同一个家庭账户很常见。",
    "Funds returning to their origin through intermediaries": "资金经中间账户回到原点",
    "Did this money travel, or only appear to?": "这笔钱真的走了一圈,还是只是看起来走了?",
    "Intra-group treasury movements between accounts of one owner look circular and are "
    "routine.":
        "同一所有人名下账户之间的集团内部资金调拨看起来就是环形的,而且很常规。",
    "A returned or reversed payment produces a two-hop cycle with an innocent cause; check "
    "whether any leg is a refund.":
        "退款或冲正会产生一个两跳的环,原因完全无辜;查一下其中是否有哪一段是退款。",
    "FX round-tripping to obtain a better rate is legal in most corridors.":
        "为拿到更好汇率而做的外汇往返操作,在多数走廊都是合法的。",
    "Activity inconsistent with the declared profile": "行为与申报画像不符",
    "Does this account behave like what the customer said it was for?":
        "这个账户的行为,像不像客户当初说的用途?",
    "A business that genuinely grew will breach its onboarding expectation; check whether "
    "the rise is sustained or a spike.":
        "真正增长的企业必然会突破开户时的预期;看一下是持续上升还是一次性尖峰。",
    "One-off events - a property sale, an inheritance, a funding round - explain a single "
    "large deviation.":
        "一次性事件——卖房、继承、一轮融资——就能解释单次的大幅偏离。",
    "A stale profile is a data problem, not a customer problem. Check when it was last "
    "reviewed before treating the gap as a signal.":
        "过期的画像是数据问题,不是客户问题。把这个落差当信号之前,先看它上次复核是什么时候。",
    "Required payment information absent or unverified": "必需的支付信息缺失或未核实",
    "Can we say who is on both ends of this money, and why it moved?":
        "这笔钱的两端分别是谁、为什么要动,我们说得清楚吗?",
    "Missing data is very often an operational defect at the sending institution, not "
    "concealment - the fix is a request for information, not an escalation.":
        "数据缺失通常是汇出机构的操作缺陷,而不是刻意隐瞒——对策是补材料,不是升级处理。",
    "Some corridors and channels legitimately carry less structured data.":
        "某些走廊和通道本来就携带较少的结构化数据。",
    "Check whether the same fields are missing across all of that channel's traffic; a "
    "systemic gap says nothing about this customer.":
        "查一下这个通道的全部流量是不是都缺同样的字段;系统性缺口和这个客户没有关系。",

    # -- dispositions and states --
    "Close — no further action": "结案 —— 不采取进一步动作",
    "The pattern is explained by the evidence on file. Closing says the alert was reviewed "
    "and understood, not that the customer was cleared of anything.":
        "在册证据已能解释这个模式。结案表示这条预警被看过并被理解了,"
        "不表示客户被排除了任何嫌疑。",
    "Keep under monitoring": "保持监测",
    "Not explained, not sufficient to escalate. The account stays in scope and the next "
    "alert on it will show this decision.":
        "解释不通,但也不足以升级。账户仍在监测范围内,它的下一条预警会显示这个决定。",
    "Request information": "补充材料",
    "A specific, named gap has to be filled before the case can be judged. The gap must be "
    "written in the reason so the request can be acted on by someone else.":
        "必须先补齐一处具体、指名的缺口,案件才能判断。缺口要写进理由里,别人才好照着去要。",
    "Send for enhanced review": "转强化复核",
    "Needs deeper work than the queue allows - a longer lookback, related accounts, or a "
    "second reviewer.":
        "需要队列节奏容不下的更深入工作——更长的回溯期、关联账户,或者第二位复核人。",
    "Escalate to the AML team": "升级至反洗钱团队",
    "Hands the case to the responsible team for a decision this system does not make. "
    "Escalation is a referral inside this prototype; it files nothing with anyone and "
    "reaches no authority.":
        "把案件交给负责团队,由他们作出这套系统不作的决定。"
        "在这个原型里,升级只是内部转交:它不向任何人提交任何东西,也不触达任何机构。",
    "close_no_action": "结案不处理",
    "continue_monitoring": "保持监测",
    "request_information": "补充材料",
    "enhanced_review": "强化复核",
    "escalate": "升级",
    "closed_no_action": "已结案不处理",
    "awaiting_information": "等待材料",
    "escalated": "已升级",
    "investigating": "调查中",
    "monitoring": "监测中",
    "new": "新建",
    "queued": "已入队",

    # -- roles and enumerations --
    "aml_investigator": "反洗钱调查员",
    "risk_ops_lead": "风险运营主管",
    "admin_auditor": "审计管理员",
    "individual": "个人",
    "business": "企业",
    "personal": "个人",
    "verified": "已核实",
    "unverified": "未核实",
    "not_required": "无需提供",
    "complete": "完整",
    "partial": "部分",
    "missing": "缺失",
    "critical": "紧急",
    "high": "高",
    "medium": "中",
    "low": "低",
}

ZH.update(ZH_AML)


# --------------------------------------------------------------------------- #
# Diagnostic reasons
#
# The guardrails and the conversation layer emit English reason strings, and
# those strings are written to the audit log verbatim. That is deliberate: an
# audit trail whose wording changes with whoever happened to be reading is not
# an audit trail. The interface still has to show them in the reader's language,
# so they are translated here, at display, and by pattern - every one of them
# carries a count, a threshold or a machine code that has to pass through
# unchanged. Order matters: the more specific pattern is listed first.
# --------------------------------------------------------------------------- #

_REASON_PATTERNS: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"^no question was asked$"), "没有提出问题"),
    (re.compile(r"^the question asked the copilot to make or take the decision: (.+)$"),
     r"该问题要求副驾代为做出或执行决策:\1"),
    (re.compile(r"^delegation of the decision was refused$"), "已拒绝交出决策权"),
    (re.compile(r"^the model provider was unreachable, so no answer was produced\. "
                r"The case, its evidence and the decision controls are unaffected\.$"),
     "模型服务不可达,未生成回答。案件、证据与决策控件均不受影响。"),
    (re.compile(r"^provider degraded: (.+)$"), r"模型服务降级:\1"),
    (re.compile(r"^the model returned something that is not a valid answer$"),
     "模型返回的内容不是一个有效回答"),
    (re.compile(r"^response was not parseable$"), "响应无法解析"),
    (re.compile(r"^the generated answer claimed an action had been taken$"),
     "生成的回答声称某个动作已被执行"),
    (re.compile(r"^the answer asserted that an action had been taken; only a person or "
                r"the deterministic policy may act, so it was discarded$"),
     "该回答断言动作已被执行;只有人或确定性策略可以执行动作,因此整条丢弃"),
    (re.compile(r"^(\d+) citation\(s\) did not resolve and were removed: (.+)$"),
     r"\1 条引用无法落地,已移除:\2"),
    (re.compile(r"^(\d+) citation\(s\) did not resolve: (.+)$"),
     r"\1 条引用无法落地:\2"),
    (re.compile(r"^the answer could not be grounded in the case or entity packets, so it "
                r"was withheld rather than shown as a guess$"),
     "该回答无法在案件包或实体包中落地,因此被扣下,而不是当作猜测展示"),
    (re.compile(r"^no citation resolved; answer withheld$"), "没有任何引用落地;回答已扣下"),
    (re.compile(r"^(\d+) PII-shaped string\(s\) redacted before display$"),
     r"展示前已脱敏 \1 处疑似个人信息"),
    (re.compile(r"^(\d+) finding\(s\) cited nothing in the case packet and were removed "
                r"as ungrounded$"),
     r"\1 条结论未引用案件包中的任何内容,已作为无依据移除"),
    (re.compile(r"^confidence scaled to ([\d.]+) because only (\d+) of (\d+) findings "
                r"were grounded$"),
     r"置信度已下调至 \1,因为 \3 条结论中只有 \2 条有依据"),
    (re.compile(r"^recommended action (.+) is not one of (.+); downgraded to abstain$"),
     r"建议动作 \1 不在 \2 之内,已降级为弃权"),
    (re.compile(r"^confidence ([\d.]+) is below the ([\d.]+) floor; recommendation "
                r"downgraded to abstain$"),
     r"置信度 \1 低于 \2 的下限,建议已降级为弃权"),
    (re.compile(r"^no grounded findings survived; recommendation downgraded to abstain$"),
     "没有任何有依据的结论留存,建议已降级为弃权"),
]


def translate_reason(text: str) -> str:
    """Render one engine reason string in the reader's language.

    Falls through to the original text rather than raising or blanking: a
    diagnostic the reader cannot understand is still better than a diagnostic
    that silently disappeared. `test_i18n.py` is what stops that fallthrough
    from becoming the normal case.
    """
    if not text or current_language() == "en":
        return text
    for pattern, replacement in _REASON_PATTERNS:
        translated, count = pattern.subn(replacement, text.strip())
        if count:
            return translated
    return text


def language_toggle() -> None:
    """The switch, top-right of the content area.

    Streamlit has no real top-right slot, so this is a narrow trailing column at
    the very top of the page. Placing it in the sidebar would have been easier
    and would have hidden it on the one screen where somebody most needs it: the
    first one they open.
    """
    spacer, control = st.columns([6, 1])
    with control:
        chosen = st.segmented_control(
            t("Language"),
            options=list(LANGUAGES),
            format_func=lambda code: LANGUAGES[code],
            default=current_language(),
            key="_language_control",
            label_visibility="collapsed",
        )
    if chosen and chosen != st.session_state.get("lang"):
        st.session_state["lang"] = chosen
        st.query_params["lang"] = chosen
        st.rerun()
    del spacer


def translation_coverage() -> dict[str, int]:
    """How much of the interface actually has a Chinese string.

    Exposed so a test can assert it rather than anyone guessing.
    """
    return {"translated": len(ZH), "language_count": len(LANGUAGES)}
